Controllers/PcContractorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessObjects.Entity;
//using BusinessLogicLayer;
using MMS_P.ViewModels;
using DataAccessLayer;
using Newtonsoft.Json;
using System.Net;

namespace MMS.Controllers
{
    public class PcContractorController : Controller
    {
        FactoryManager m = new FactoryManager();

        static private List<tblRegistrationType> VendorGroupList;
        string Id = "0";
        string EmpID = null;
        private tblRegistrationType VendorGroup;


        public PcContractorController()
        {
            try
            {
                EmpID = System.Web.HttpContext.Current.Session["EmpID"].ToString();


            }
            catch
            {
            }
        }

        private void FIllBySession()
        {
            if (System.Web.HttpContext.Current.Session["Id"] != null)
                Id = System.Web.HttpContext.Current.Session["Id"].ToString();

            VendorGroup = VendorGroupList.Where(a => a.TypeID == Id).FirstOrDefault();

        }

        private void FIllByid(int? id)
        {


            VendorGroup = VendorGroupList.Where(a => a.TypeID == Id).FirstOrDefault();

        }

        public ActionResult Index()

        {
            ViewBag.VGId = new SelectList(m.GetVendorGroupManager().FindPCAll(), "TypeId", "RegistrationType", Id);
            return View();
        }

        public ActionResult Grid(string VGId = "0", int page = 1, string sort = "Name", string sortDir = "ASC")
        {
            const int pageSize = 15000;
            sortDir = sortDir.Equals("desc", StringComparison.CurrentCultureIgnoreCase) ? sortDir : "asc";
            var validColumns = new[] { "PcContractorID", "Name", "City" };
            if (!validColumns.Any(c => c.Equals(sort, StringComparison.CurrentCultureIgnoreCase)))
                sort = "PcContractorID";

            if (VGId != "0")
            {
                Id = VGId;
                this.Session["Id"] = Id.ToString();
            }
            else
            {
                try { FIllBySession(); }
                catch { }
            }
            if (Id == "0")
            {
                //Id = "VID0000001";
                this.Session["Id"] = Id;
            }

            if (Id != "0")
            {
                //VendorGroup = VendorGroupList.Where(a => a.TypeID == Id).FirstOrDefault();
                VendorGroup = m.GetVendorGroupManager().Find(Id);
                if (VendorGroup != null)
                {
                    var totalRows = m.GetPcContractorMasterManager().CountByVendorGroup(VendorGroup.TransID);
                    var VendorMasters = m.GetPcContractorMasterManager().FindPageByVendorGroup(VendorGroup.TransID, page, pageSize);
                    var ven = m.GetPcContractorMasterManager().FindPageByVendorGroupNew(VendorGroup.TypeID, page, pageSize);
                    //var VendorMasters = m.GetVendorMasterManager().FindPageByVendorGroup(VendorGroup.TypeID, page, pageSize);

                    var data = new PageVendorMasterModelPage()
                    {
                        TotalRows = totalRows,
                        PageSize = pageSize,
                        //  VendorMasterBll = VendorMasters.ToList()
                        PcContractorrMasterBll = ven.ToList()
                    };
                    return View("_GridView", data);
                }
                else { return View("_EmptyView"); }
            }
            else { return View("_EmptyView"); }
        }

        // GET: tblVendorMasters/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPcContractorMaster vendorMaster = m.GetPcContractorMasterManager().Find((int)id);

            try
            {
                // just added viewbag for projid

                vendorMaster.Country = m.GetCountryMasterManager().FindCountryName(vendorMaster.Country);
                vendorMaster.State = m.GetCountryMasterManager().FindStateName(vendorMaster.State);
                vendorMaster.City = m.GetCountryMasterManager().FindCityName(vendorMaster.City);
            }
            catch { }

            if (vendorMaster == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
            {


                return PartialView(vendorMaster);
            }
            else
                return View(vendorMaster);
        }

        // GET: tblVendorMasters/Create
        public ActionResult Create()
        {



            ViewBag.Country = new SelectList(m.GetCountryMasterManager().FindAllCountry(), "CountryID", "CnName", "FD49C22E-4C33-4DEA-BC9E-0EDBD7F191E4");
            try
            {

                ViewBag.State = new SelectList(GetState("FD49C22E-4C33-4DEA-BC9E-0EDBD7F191E4"), "StateID", "StateName");

            }
            catch
            {

            }


            ViewBag.PRJID = new SelectList(m.GetProjectMasterManager().FindAll(), "PRJID", "ProjectName");
             //ViewBag.RegistrationType = new SelectList(m.GetVendorGroupManager().FindAll(), "TypeId", "RegistrationType", Id);
            ViewBag.RegistrationType = new SelectList(m.GetVendorGroupManager().FindOnlyPettyContractorPC(), "TypeId", "RegistrationType", Id);
            ViewBag.VendorTypeCode = new SelectList(m.GetVendorTypeManager().FindAll(), "TypeId", "VendorType");

            if (Request.IsAjaxRequest())
            {
                ViewBag.IsUpdate = false;
                return PartialView();
            }
            else
                return View();
        }
        [HttpPost]
        public ActionResult GetStateByCountryId(string CountryId)
        {
            var S = GetState(CountryId);

            SelectList State = new SelectList(S, "StateID", "StateName");
            return Json(State);
        }
        private List<tblState> GetState(string CountryId)
        {

            try
            {
                if (CountryId != null)
                    return m.GetCountryMasterManager().FindAllState(CountryId);
                else
                    return null;
            }
            catch { return null; }



        }
        [HttpPost]
        public ActionResult GetCityByStateId(string StateId)
        {
            var C = GetCity(StateId);

            SelectList City = new SelectList(C, "CityID", "CityName");
            return Json(City);
        }
        private List<tblCityList> GetCity(string StateId)
        {
            try
            {
                if (StateId != null)
                {
                    return m.GetCountryMasterManager().FindAllCity(StateId);
                }
                else
                    return null;

            }
            catch { return null; }



        }

        [HttpPost]
       // [ValidateAntiForgeryToken]
        public ActionResult Create(TestVendorClass VData)
        {
            bool IsPan;
            tblPcContractorMaster vm = new tblPcContractorMaster();
            vm.CreatedDate = System.DateTime.Now;
            vm.CreatedBy = EmpID;

            string PRJID = String.Empty; string RegTYpeID = String.Empty;
            string[] ss = VData.PRID; string[] rty = VData.MulRegistrationType;
            foreach (string value in ss)
            {
                PRJID += value;
                PRJID += ",";
            }
            vm.PRJID = PRJID.TrimEnd(',');


            foreach (string value1 in rty)
            {
                RegTYpeID += value1;
                RegTYpeID += ",";
            }

            vm.MulRegistrationType = RegTYpeID.TrimEnd(',');

            vm.TinNo = VData.TinNo;
            vm.PanNo = VData.PanNo;
            vm.Name = VData.VendorName;
            vm.Address = VData.Address.Trim();
            vm.Country = VData.Country.Trim();
            vm.State = VData.State.Trim();
            vm.City = VData.City.Trim();
            vm.PinCode = VData.PinCode;
            vm.Status = VData.Status;
            vm.BlackListStatus = VData.BlackListStatus;
            vm.ContactPerson = VData.ContactPerson;
            vm.MobileNo = VData.MobileNo;
            vm.PhoneNo = VData.PhoneNo;
            vm.Email = VData.Email;
            vm.RegistrationType = "TID0000001";
            // vm.CompanyID = Session["CompanyId"].ToString();
            vm.CompanyID = "COMP000001";
            IsPan = m.GetRepeatChequeManager().PcContractorPanNoCheck(VData.PanNo);
            if (IsPan == true)
            {

           
            int i = m.GetPcContractorMasterManager().Add(vm);
            if (i != 0)
            {

                if (Request.IsAjaxRequest())
                {

                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }

            ViewBag.Country = new SelectList(m.GetCountryMasterManager().FindAllCountry(), "CountryID", "CnName");
            ViewBag.RegistrationType = new SelectList(m.GetVendorGroupManager().FindPCAll(), "TypeId", "RegistrationType", Id);
            ViewBag.PRJID = new SelectList(m.GetProjectMasterManager().FindAll(), "PRJID", "ProjectName");
            ViewBag.VendorTypeCode = new SelectList(m.GetVendorTypeManager().FindAll(), "TypeId", "VendorType");


            return Json("1", JsonRequestBehavior.AllowGet);
            }
            else {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }


        public JsonResult IsVendorNameUnique(tblPcContractorMaster catalog)
        {

            return m.GetRepeatChequeManager().PcContractorNameRepeat(catalog.Name, catalog.RegistrationType, catalog.TransID)
                ? Json(false, JsonRequestBehavior.AllowGet)

Views/PcContractor/Index.cshtml
@model MMS_P.ViewModels.PageVendorMasterModelPage

@{
    ViewBag.Title = "Index";
    string layout = "";
    var cheking = Session["EmailCheck"].ToString();
    if (cheking == "admin@sitanet.in")
    {
        layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
    else
    {
        layout = "~/Views/Shared/_Layout.cshtml";//
    }

    Layout = layout;
}

<script>
    Url =
function () { }
    Url.prototype = {
        _relativeRoot: '<%= ResolveUrl("~/") %>',
        // create an extension method called "resolve"
        resolve: function (relative) {
            var resolved = relative;
            if (relative.charAt(0) == '~')
                resolved = this._relativeRoot + relative.substring(2);
            return resolved;
        }
    }
    $Url = new Url();

</script>

<script>
          // Fill Grid At Load Time
    $(document).ready(function () {

        //function getJob() {
        @*$.post('@Url.Content("~/tblVendorsMasters/Grid/")', function (data) {*@
        $.post('@Url.Action("Grid", "PcContractor")', function (data) {
                $('#formbody').html("");
                $('#formbody').html(data);
            });
        //}

    });
    // Fill Grid for Paging
    $(document).on("click", "#myPager a", function () {
        //var url = "/tblItemMasters/Grid/";
        $.ajax({

            url: $(this).attr("href"),
            type: 'GET',
            cache: false,
            success: function (result) {
                $('#formbody').html(result);
            }
        });
        return false;
    });



    // Fill Grid for List Selection
    function getblock(_siteid) {
        //alert("you clicked the paragraph getBlock ");
        if (_siteid != 0) {

            //var url = $Url.resolve("~/tblVendorMasters/Grid/");
            var url = '@Url.Action("Grid", "PcContractor")';
            //var url = "/tblVendorMasters/Grid/";
            $('#progress').show();
            $.ajax({
                //url: $('#ddlItemG').attr("url"),
                url: url,
                type: 'GET',
                data: { VGId: $('#ddlItemG').val() },
                complete: function () {
                    $('#progress').hide();
                },
                success: function (result) {
                    $('#formbody').html(result);
                }
            });
            return false;
        }
    }
</script>

<section id="content_wrapper">

    <section id="content" class="table-layout animated fadeIn">


        <div class="tray tray-center">

            <div class="mw1000 center-block">

                <div class="admin-form">

                    <div class="panel heading-border">
                        <div class="panel-body bg-light">
                            <form method="post" action="#" id="form-ui">
                                <div class="section-divider mb40" id="spy1">
                                    <span>PC Contractor Master</span>
                                </div>

                                <div class="row">
                                    <div class="well">
                                        @using (Html.BeginForm("index", null, FormMethod.Get))
                                        {
                                            <div class="row">
                                                <div class="col-sm-8">
                                                    <div class="input-group">
                                                        <div class="col-md-10">
                                                            <label class="field select">
                                                                @*@{var U=@Url.Action("tblVendorMasters", "Grid");}*@
                                                                @Html.DropDownList("VGId", null, "Select List", htmlAttributes: new { @id = "ddlItemG", @class = "form-control", onchange = "javascript:getblock(this.value);", url = @Url.Action("Grid", "PcContractor") })

                                                                <i class="arrow"></i>
                                                            </label>
                                                        </div>

                                                        <div class="pull-right col-lg-1">
                                                            <a class="btn btn-primary" data-modal="" href="@Url.Action("Create","PcContractor" )" id="btnCreate">

                                                                Create New
                                                            </a>

                                                        </div>
                                                    </div>
                                                </div>


                                            </div>
                                        }


                                    </div>
                                </div>
                            </form>

                            @*<form action="Create" method="post">*@
                            <div class="pager glyphicon-align-center" id="formbody">
                                @*@{Html.RenderAction("Grid", "tblVendorMasters");}*@
                            </div>


                            @*</form>*@
                        </div>
                        <div class="section-divider mt40 mb25" id="spy5">
                            <span></span>
                        </div>



                    </div>
                </div>

            </div>

        </div>


    </section>

</section>

Views/PcContractor/SubmitForm.cshtml
@model BusinessObjects.Entity.tblPcContractorMaster
@{
    ViewBag.Title = "SubmitForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script language="javascript" type="text/javascript">

    function GetState(_CountryId)
    {
        var procemessage = "<option value='0'> Please wait...</option>";
        $("#ddlState").html(procemessage).show();
        //var url = "/tblVendorMasters/GetStateByCountryId/";
        var url = '@Url.Action("GetStateByCountryId", "PcContractor")';
        $.ajax({
            url: url,
            data: { CountryId: _CountryId },
            cache: false,
            type: "POST",
            success: function (data) {
                var markup = "<option value='0'>Select State</option>";
                for (var x = 0; x < data.length; x++) {
                    markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";

                }
                $("#ddlState").html(markup).show();
            },

            error: function (reponse) {
                alert("error : " + reponse);
            }
        });
    }
    function GetCity(_StateId)
    {
        var procemessage = "<option value='0'> Please wait...</option>";
        $("#ddlCity").html(procemessage).show();
        //var url = "/tblVendorMasters/GetCityByStateId/";
        var url = '@Url.Action("GetCityByStateId", "PcContractor")';
        $.ajax({
            url: url,
            data: { StateId: _StateId },
            cache: false,
            type: "POST",
            success: function (data) {
                var markup = "<option value='0'>Select City</option>";
                for (var x = 0; x < data.length; x++) {
                    markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";

                }
                $("#ddlCity").html(markup).show();
            },

            error: function (reponse) {
                alert("error : " + reponse);
            }
        });
    }
    $('#btnsave').click(function (event)
    { alert("A");
        var valid = ValidMaster();
        if (valid == false)
        {
            event.preventDefault();
            $j('#Submit').attr('onclick', '').unbind('click');
        }

    });

    function ValidMaster()
    {
        alert("B");
        var rr = true;
        var RegistrationType = $("#RegistrationType option:selected").val();
        if (RegistrationType == "0" || RegistrationType == "")
        {
            $('#RegistrationType').css('border-color', '#f0551b');
            alert("Select RegistrationType");
            rr = false;
        }
        else
        {
            $('#RegistrationType').css('border-color', '');

        }


        var PRJID = $("#PRJID option:selected").val();
        if (PRJID == "0" || PRJID == "") {
            $('#PRJID').css('border-color', '#f0551b');
            alert("Select Project");
            rr = false;
        }
        else {
            $('#PRJID').css('border-color', '');

        }

        return rr;

    }
</script>



@using (Html.BeginForm("SubmitForm", "PcContractor", FormMethod.Post))
{
    <div class="main-Background">
        ******lots of other html here*******
        <button type="submit" id="btnSave">Save</button>

    </div>
}

Views/PcContractor/_GridView.cshtml
@model MMS_P.ViewModels.PageVendorMasterModelPage
@{
    ViewBag.Title = "_GridView";
    Layout = null;
}


<style>
    .webgrid-header td, th {
        background-color: #72AAD3; /*#D3D3D3; color: #6D70B5;*/
        padding-bottom: 4px;
        padding-top: 5px;
        text-align: center;
        border-bottom: 1px solid white;
        border-top: 1px solid white;
        margin-bottom: 2px;
        padding: 0px 5px;
        text-align: center;
        height: 22px;
        color: white;
        font-weight: bold;
    }
</style>


<div id="myPager" style="margin-top:17px;">
    @{
        var grid = new WebGrid(
                        canPage: true,
                        rowsPerPage: Model.PageSize,
                        canSort: true,

                        ajaxUpdateContainerId: "grid");

        grid.Bind(Model.PcContractorrMasterBll, rowCount: Model.TotalRows, autoSortAndPage: false);
        grid.Pager(WebGridPagerModes.All);

        @grid.GetHtml(htmlAttributes: new { id = "grid" },
                      headerStyle: "webgrid-header",
            //headerStyle: "text-align: center",
            fillEmptyRows: false,
            tableStyle: "table table-bordered table-hover",
            mode: WebGridPagerModes.All,
            columns: grid.Columns(
                                                   grid.Column("tblPC_RegistrationType.RegistrationType", header: "Group", style: "text-align: center;"),
                                                      grid.Column("Name", header: "Name", style: "text-align: center"),
                                                      grid.Column(header: " Action ", canSort: false, style: "action",
                                                  format: @<text>
                                                        @*@Html.Raw("<a data-modal='' href='/tblVendorMasters/details/" + item.TransID + "' id='" + item.TransID + "' title='Detail' > <span class='glyphicon glyphicon-search'> </span> </a>")
                                                            @Html.Raw("<a data-modal='' href='/tblVendorMasters/edit/" + item.TransID + "' id='" + item.TransID + "' title='Edit'> <span class='glyphicon glyphicon-edit'> </span> </a>")
                                                            @Html.Raw("<a data-modal='' href='/tblVendorMasters/delete/" + item.TransID + "' id='" + item.TransID + "' title='Delete'> <span class='glyphicon glyphicon-trash'> </span> </a>")*@
                                                        <a data-modal='' href='@Url.Action("Details", "PcContractor", new { id = item.TransID })' id='@item.TransID' title='Detail'> <span class='glyphicon glyphicon-search'> </span> </a>
                                                        <a data-modal='' href='@Url.Action("Edit", "PcContractor", new { id = item.TransID })' id='@item.TransID' title='Edit'> <span class='glyphicon glyphicon-edit'> </span> </a>
                                                        <a data-modal='' href='@Url.Action("Delete", "PcContractor", new { id = item.TransID })' id='@item.TransID' title='Delete'> <span class='glyphicon glyphicon-trash'> </span> </a>
                                                </text>)

                                                                                                                                            ));
    }


</div>