ViewModels/UpdateMRNTRN.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MMS.ViewModels
{
    public class UpdateMRNTRN
    {
        public Int64 Sno { get; set; }
        public decimal UId { get; set; }
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string IntraTransferNumber { get; set; }
        public string TransferDate { get; set; }
        public string MRNDate { get; set; }
        public string MRN_No_New { get; set; }
        public string GateEntryMidNo { get; set; }
        public string GateEntryMidDate { get; set; }
      

    }
}

ViewModels/UpdatedMRN.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MMS.ViewModels
{
    public class UpdatedMRN
    {
        public Int64 Sno { get; set; }
        public decimal UId { get; set; }

        public string PurchaseOrderNo { get; set; }
        public string IndentRefNo { get; set; }
        public string Name { get; set; }
        public string PurchaseOrderDate { get; set; }
        public string PIDate { get; set; }
        public string MRNDate { get; set; }
        public string MRN_No_New { get; set; }
        public string GateEntryMidNo { get; set; }
        public string GateEntryMidDate { get; set; }
        public string ProjectNo { get; set; }
        public string PurchasePIC_Type { get; set; }
        public string VendorID { get; set; }
    }
}

Controllers/MRNListClassificationController.cs
using MMS.DAL;
using MMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace MMS.Controllers
{
    public class MRNListClassificationController : Controller
    {
        // GET: MRNListClassification
        private MMSEntities objmms = new MMSEntities();
        string EmpId = string.Empty;
        Procedure objp = new Procedure();
        public MRNListClassificationController()
        {
            try
            {
                EmpId = System.Web.HttpContext.Current.Session["EmpId"].ToString();


            }
            catch
            {
            }
        }
        public ActionResult Index()
        {
            if (Session["EmpID"] == null)
            {
                return RedirectToAction("Login", "MyAccount");
            }
            ViewBag.EmpId = EmpId;
            return View();
        }

        public ActionResult PendingMRN(string ProjId, string PurchaseType,string VendorId , string PurchaseOrderNo)
        {
            List<MMS.ViewModels.PendingMRN> res = new List<ViewModels.PendingMRN>();
            res = null;
            res = objp.GetPendingMRNGST(ProjId, PurchaseType);

            if (VendorId != "0" && PurchaseOrderNo != "")
            {
                res = res.ToList().Where(x => x.VendorID == VendorId && x.PurchaseOrderNo == PurchaseOrderNo).ToList();
            }
            else if (VendorId != "0" && PurchaseOrderNo == "")
            {
                res = res.ToList().Where(x => x.VendorID == VendorId).ToList();
            }
            else if (VendorId == "0" && PurchaseOrderNo != "")
            {
                res = res.ToList().Where(x =>x.PurchaseOrderNo == PurchaseOrderNo).ToList();
            }

            if (res != null)
            {
                return PartialView("_PartialMRN", res);
            }
            else
            {
                return PartialView("_EmptyView");
            }
        }

        public ActionResult UpdatedMRN(string ProjId, string PurchaseType)
        {
            List<MMS.ViewModels.UpdatedMRN> res = new List<ViewModels.UpdatedMRN>();
            res = null;
          //  res = objp.GetUpdatedMRNGST(ProjId, PurchaseType);
            res = objp.GetUpdatedMRNGST(ProjId, Convert.ToString(2));
            if (res != null)
            {
                return PartialView("_TestUpdatedMRN", res);
            }
            else
            {
                return PartialView("_EmptyView");
            }
        }

        public ActionResult PendingMRNTRN(string ProjId, string PurchaseType, string fromSiteId, string PurchaseOrderNo)
        {
          
            List<MMS.ViewModels.PendingTransferMRN> res = new List<ViewModels.PendingTransferMRN>();
            res = null;
            res = objp.GetPendingMRNTRN(ProjId, PurchaseType);
            if (fromSiteId != "0" && PurchaseOrderNo != "")
            {
                res = res.ToList().Where(x => x.ProjectId == fromSiteId && x.IntraTransferNumber == PurchaseOrderNo).ToList();
            }
            else if (fromSiteId != "0" && PurchaseOrderNo == "")
            {
                res = res.ToList().Where(x => x.ProjectId == fromSiteId).ToList();
            }
            else if (fromSiteId == "0" && PurchaseOrderNo != "")
            {
                res = res.ToList().Where(x => x.IntraTransferNumber == PurchaseOrderNo).ToList();
            }
           if (res != null)
            {
                ViewBag.PurchaseType = PurchaseType;
                return PartialView("_PendingTRNMRN", res);
            }
            else
            {
                return PartialView("_EmptyView");
            }
           


        }
      [HttpPost]
        public ActionResult UpdatedMRN_TRN(string ProjId, string PurchaseType, string fromSiteId, string PurchaseOrderNo)
        {
             int recordsTotal = 0;
             var draw = Request.Form.GetValues("draw").FirstOrDefault();
            if (ProjId != null && PurchaseType != null)
            {

                var lst = objp.GetUpdatedMRNGST_TRN(ProjId, Convert.ToString(PurchaseType));
                ViewBag.PurchaseType = PurchaseType;
                if (fromSiteId != "0" && PurchaseOrderNo != "")
                {
                    lst = lst.ToList().Where(x => x.ProjectId == fromSiteId && x.IntraTransferNumber == PurchaseOrderNo).ToList();
                }
                else if (fromSiteId != "0" && PurchaseOrderNo == "")
                {
                    lst = lst.ToList().Where(x => x.ProjectId == fromSiteId).ToList();
                }
                else if (fromSiteId == "0" && PurchaseOrderNo != "")
                {
                    lst = lst.ToList().Where(x => x.IntraTransferNumber == PurchaseOrderNo).ToList();
                }

                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                recordsTotal = lst.ToList().Count();
                var data = lst.Skip(skip).Take(pageSize).ToList();
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data }, JsonRequestBehavior.AllowGet);
            }
            else {
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = 0 }, JsonRequestBehavior.AllowGet);
            }


        }


        // for testing Purchase
        [HttpPost]
        public ActionResult UpdatedMRN_NewFormat(string ProjId, string PurchaseType, string VendorId, string PurchaseOrderNo)
        {
            int recordsTotal = 0;
          //  var projId = Request.Form.GetValues("columns[9][search][value]").FirstOrDefault();
          //  var Purchse_typeid = Request.Form.GetValues("columns[10][search][value]").FirstOrDefault();
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            if (ProjId != null && PurchaseType != null )
            {

                var lst = objp.GetUpdatedMRNGST(ProjId, Convert.ToString(PurchaseType));

                if (VendorId != "0" && PurchaseOrderNo != "")
                {
                    lst = lst.ToList().Where(x => x.VendorID == VendorId && x.PurchaseOrderNo == PurchaseOrderNo).ToList();
                }
                else if (VendorId != "0" && PurchaseOrderNo == "")
                {
                    lst = lst.ToList().Where(x => x.VendorID == VendorId).ToList();
                }
                else if (VendorId == "0" && PurchaseOrderNo != "")
                {
                    lst = lst.ToList().Where(x => x.PurchaseOrderNo == PurchaseOrderNo).ToList();
                }







                //Get parameters

                // get Start (paging start index) and length (page size for paging)

                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                //Get Sort columns value
                //  var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                // var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();

                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;



              

                



                recordsTotal = lst.ToList().Count();
                var data = lst.Skip(skip).Take(pageSize).ToList();
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data }, JsonRequestBehavior.AllowGet);
            }
            else {
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = 0 }, JsonRequestBehavior.AllowGet);
            }
            //  return Json(new DataTablesResponse(requestModel.Draw, data, filteredCount, totalCount), JsonRequestBehavior.AllowGet);
          
        }


     
    

        // end

        public JsonResult BindEmployeePurchaseType()
        {
            string J = null; string EmpId = string.Empty;
            EmpId = System.Web.HttpContext.Current.Session["EmpId"].ToString();
            string PurchIds = objmms.tblEmployeeMasters.Where(x => x.EmpID == EmpId).ToList().FirstOrDefault().PurchaseType;
            if (PurchIds != null)
            {
                string[] purtyps = PurchIds.Split(',');
                var a = objmms.tblPI_PurchaseType.Where(xx => purtyps.Contains(xx.TrandId.ToString()) && xx.TrandId > 0).Select(y => new { Text = y.PurchaseType, Value = y.TrandId }).OrderBy(s => s.Text).ToList();
                J = a.ToJSON();
                return Json(J, JsonRequestBehavior.AllowGet);

            }
            else
            {
                return Json(J, JsonRequestBehavior.AllowGet);

            }
        }

        public JsonResult GetMRS(string MRN_NO)
        {
             List<MMS.ViewModels.MRS> lst = null;
          
            lst = objp.GetMRS(MRN_NO);
            if (lst != null)
            {
               
                return Json(lst.ToJSON(), JsonRequestBehavior.AllowGet);
            }
            else
            {

                return null;
            }
        }

        public JsonResult GetMRSatTRANS(string MRN_NO, string PurTypeId)
        {
            List<MMS.ViewModels.MRS> lst = null;
            if (PurTypeId == "5")
            { lst = objp.GetMRS_TRANS_Inter(MRN_NO); } else if(PurTypeId == "6") { lst = objp.GetMRS_TRANS_Intra(MRN_NO); }

           
            if (lst != null)
            {

Views/MRNListClassification/Index.cshtml
@{
    ViewBag.Title = "Index";
    string layout = "";
    var cheking = Session["EmailCheck"].ToString();
    if (cheking == "admin@sitanet.in")
    {
        layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
    else
    {
        layout = "~/Views/Shared/_Layout.cshtml";
    }

    Layout = layout;
}



<script src="~/Scripts/jquery-2.1.1.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<link href="@Url.Content("~/Content/themes/base/minified/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
@*<link href="//cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css" rel="stylesheet" />*@
<style type="text/css">
    .th-bg{
    background:#4a89dc !important;
}
</style>

<script type="text/javascript">
    var ss = @Html.Raw(Json.Encode(ViewBag.EmpId));
    var GetProjectByEmpId = '@Url.Action("GetProjectByEmpId","tblItemMasters")';
    var getPurchaseTypeForLoggedEmployee = '@Url.Action("BindEmployeePurchaseType", "MRNListClassification")';
    var getpendingMRN = '@Url.Action("PendingMRN", "MRNListClassification")';
    var getUpdatedMRN = '@Url.Action("UpdatedMRN", "MRNListClassification")';
    var getVendorList = '@Url.Action("GetVendorListByprojectWise", "MRNListClassification")';
    var getpendingMRNTRN = '@Url.Action("PendingMRNTRN", "MRNListClassification")';
    var getUpdatedMRNTRN = '@Url.Action("UpdatedMRN_TRN", "MRNListClassification")';
    var BindFromSiteList = '@Url.Action("GetFromSiteNamefromTransferList", "MRNListClassification")';

</script>

<script type="text/javascript">
   
</script>

<section id="content_wrapper">
    <!-- Begin: Content -->
    <section id="content" class="table-layout animated fadeIn">

        <!-- begin: .tray-center -->
        <div class="tray tray-center">

            <div class="mw1000 center-block">
                <div class="admin-form theme-primary">
                    <!-- Begin: Content Header -->
                    <!-- Begin: Admin Form -->
                    <div class="form-headerStyle theme-primary">

                        <div class="panel heading-border">
                            <div class="panel-body bg-light">
                                <div class="section-divider mb40" id="spy1">
                                    <span style="color:#4a89dc">MRN Entry </span>
                                </div>




                                <div class="panel">
                                    <div class="panel-heading">

                                        <div class="panel-body">
                                            <div class="row">
                                                <div class="col-md-3">
                                                    <div class="section">
                                                        <label class="field select">
                                                            @Html.DropDownList("Project", new SelectList(string.Empty, "Value", "Text"), "Select Project Assign", htmlAttributes: new { @id = "Project", @class = "form-control" })
                                                            <i class="arrow"></i>
                                                        </label>
                                                    </div>

                                                </div>

                                                <div class="col-md-2">
                                                    <div class="section">
                                                        <label class="field select">
                                                            @Html.DropDownList("PurchaseType", new SelectList(string.Empty, "Value", "Text"), "Select Purchase Type", htmlAttributes: new { @id = "ddlPurchaseType", @class = "form-control" })
                                                            <i class="arrow"></i>
                                                        </label>
                                                    </div>
                                                </div>

                                                <div class="col-md-3" id="vndr_drp">
                                                    <div class="section">
                                                        <label class="field select">
                                                            @Html.DropDownList("Vendor", new SelectList(string.Empty, "Value", "Text"), "Select Vendor Name", htmlAttributes: new { @id = "ddlVendorlist", @class = "form-control" })
                                                            <i class="arrow"></i>
                                                        </label>
                                                    </div>
                                                </div>

                                                <div class="col-md-3" id="frmid_drp">
                                                    <div class="section">
                                                        <label class="field select">
                                                            @Html.DropDownList("FromSite", new SelectList(string.Empty, "Value", "Text"), "Select Site Name", htmlAttributes: new { @id = "ddlFromSiteName", @class = "form-control" })
                                                            <i class="arrow"></i>
                                                        </label>
                                                    </div>
                                                </div>


                                                <div class="col-md-2">
                                                    @Html.TextBox("PurchaseOrder", null, new { id = "txtPurchaseOrderNo", @class = "form-control gui-input required", @PlaceHolder = "Purchase Order No. " })
                                                </div>
                                                  
                                                  <div class="col-md-2">
                                                      <input type="button" id="btn_Search" class="btn btn-primary" value="Search" />

                                                  </div>

                                            </div>


                                        </div>

                                        <div class="container tabs-wrap">

                                            <div class="container tabs-wrap">
                                                <ul class="nav nav-tabs nav-tabs-border" role="tablist">
                                                    <li role="presentation" class="active">
                                                        <a href="#pendingMRNdetail" aria-controls="pendingMRNdetail" role="tab" data-toggle="tab" aria-expanded="true">Pending MRN</a>
                                                    </li>
                                                   
                                                    <li>
                                                        <a href="#updatedMRNdetail" aria-controls="updatedMRNdetail" role="tab" data-toggle="tab" aria-expanded="false">Updated MRN</a>
                                                    </li>
                                                </ul>


                                                <div class="panel-body">
                                                    <div class="tab-content pn br-n">
                                                        <div role="tabpanel" class="tab-pane active" id="pendingMRNdetail">

                                                            <div class="row">


                                                                @Html.AntiForgeryToken()

                                                                <div class="form-horizontal">


                                                                    <div class="row">

                                                                        <div id="dvLoading"></div>
                                                                        <div id="#progress" style="display:none"><img src="~/Images/36.gif" /></div>
                                                                        <div class="pager glyphicon-align-center" id="formbody">


                                                                        </div>

                                                                        <div class="section-divider mt40 mb25" id="spy5">
                                                                            <span></span>
                                                                        </div>


                                                                    </div>



                                                                </div>


                                                            </div>


                                                        </div>

                                                       

                                                        <div role="tabpanel" class="tab-pane" id="updatedMRNdetail">

                                                            <div class="row">

                                                                <div class="form-horizontal">
                                                                    @*<div class="row">

                                                                        <div class="row">
                                                                            <div class="col-md-12">
                                                                                <div id="dvLoading"></div>
                                                                                <div id="#progress" style="display:none"><img src="~/Images/36.gif" /></div>
                                                                            </div>
                                                                            <div class="col-md-4"></div>
                                                                        </div>

                                                                        <div class="pager glyphicon-align-center" id="formbodyUpdatedMRN">

                                                                        </div>


                                                                    </div>*@

                                                                    <div class="row">
                                                                        <div class="col-md-12">
                                                                            <div class="panel panel-primary list-panel" id="list-panel">

                                                                                <div class="panel-body" id="nottr_mrn">
                                                                             
                                                                               <table id="assets-data-table" class="table table-responsive table-striped primary" style="width:100%;"></table>
                                                                                </div>

                                                                                <div class="panel-body" id="tr_mrn">

                                                                                <table id="trtbleid" class="table table-responsive table-striped primary" style="width:100%;"></table>
                                                                                </div>

                                                                            </div>
                                                                        </div>
                                                                    </div>




                                                                </div>


                                                                <br />
                                                                <div>


                                                                    <div style="visibility:hidden;" id="container"></div>

                                                                </div>

                                                                <div class="section-divider mt40 mb25" id="spy5">
                                                                    <span></span>
                                                                </div>

                                                            </div>

                                                        </div>




                                                    </div>
                                                </div>

                                            </div>

                                        </div>

                                    </div>
                                </div>
                            </div>

                        </div>



                    </div>
                </div>
            </div>
        </div>
        <!-- end: .tray-center -->
        <!-- begin: .tray-right -->
        <!-- end: .tray-right -->

    </section>
    <!-- End: Content -->
</section>


<link href="//cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css" rel="stylesheet" />


@section Scripts
{
  <script src="~/Script/jquery.dataTables.min.js"></script>

   <script src="~/Script/MRNList.js"></script>
 }

Views/MRNListClassification/_GridItemdetail.cshtml
@model IEnumerable<MMS.ViewModels.GetMSRItemDetail>


<table class="table-bordered" style="width:100%; font-size:8px;" cellpadding="4" cellspacing="0" border="1">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SNo)
        </th>
        <th> @Html.DisplayNameFor(model => model.Item) </th>
        <th>
            @Html.DisplayNameFor(model => model.Unit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MRN_Receive)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="font-size:10px;">
                @Html.DisplayFor(modelItem => item.SNo)

            </td>
            <td style="font-size:10px;">
                @Html.DisplayFor(modelItem => item.Item)
            </td>
            <td style="font-size:10px;">   
                @Html.DisplayFor(modelItem => item.Unit)
            </td>
            <td style="font-size:10px;">
                @Html.DisplayFor(modelItem => item.MRN_Receive)
            </td>

        </tr>
    }

</table>

Views/MRNListClassification/_UpdatedMRN.cshtml
<style>
    .gridTable {
        margin: 5px;
        padding: 10px;
        border: 1px #c8c8c8 solid;
        border-collapse: collapse;
        min-width: 550px;
        background-color: #fff;
        color: #fff;
        width: 100%;
    }

    .gridHead th {
        font-weight: bold;
        background-color: #5c93f0;
        color: #fff;
        padding: 5px;
        text-align: center;
        font-size: 12px;
    }

    .gridHead a:link, .gridHead a:visited, .gridHead a:active, .gridHead a:hover {
        color: #fff;
    }

    .gridHead a:hover {
        text-decoration: underline;
    }

    .gridTable tr.gridAltRow {
        background-color: #efeeef;
    }

    .gridTable tr:hover {
        background-color: #7da3f2;
    }

    .gridTable tr :hover {
        color: white;
    }

    .gridAltRow td {
        padding: 10px;
        margin: 5px;
        color: #333;
        text-align: left;
        font-weight: normal;
        font-size: 11px;
    }

    .gridRow td {
        padding: 10px;
        color: #333;
        text-align: left;
        font-weight: normal;
        font-size: 11px;
    }

    .gridFooter td {
        padding: 10px;
        color: #ffffff;
        font-size: 12pt;
        text-align: center;
        background-color: #5c93f0;
    }

    .aaaa {
        width: 60px;
    }




    .gridFooter a {
        text-decoration: none;
        padding: 6px 11px;
        margin-right: 6px;
        border-radius: 3px;
        color: #fff;
        text-shadow: 0px 1px 2px rgba(0, 0, 0, 0.5);
        border: 1px solid #43505e;
        background: #556270;
        background: -moz-linear-gradient(top, #556270 0%, #444d57 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#556270), color-stop(100%,#444d57));
        background: -webkit-linear-gradient(top, #556270 0%,#444d57 100%);
        background: -o-linear-gradient(top, #556270 0%,#444d57 100%);
        background: -ms-linear-gradient(top, #556270 0%,#444d57 100%);
        background: linear-gradient(to bottom, #556270 0%,#444d57 100%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#556270', endColorstr='#444d57',GradientType=0 );
        -moz-box-shadow: inset 0 3px 0px -2px rgba(255, 255, 255, .3);
        -webkit-box-shadow: inset 0 3px 0px -2px rgba(255, 255, 255, .3);
        box-shadow: inset 0 3px 0px -2px rgba(255, 255, 255, .3);
    }
</style>


<div id="gridposition" class="table-responsive" style="width: 100%; overflow:scroll">
    @if (Model.Count > 0)
    {
        var grid1 = new WebGrid(source: Model, canPage: true, rowsPerPage: 20, ajaxUpdateContainerId: "positionGrid");

        @grid1.GetHtml(mode: WebGridPagerModes.All,
                   tableStyle: "gridTable",
                   headerStyle: "gridHead",
                   footerStyle: "gridFooter",
                   rowStyle: "gridRow",
                   alternatingRowStyle: "gridAltRow",
                   htmlAttributes: new { id = "positionGrid" },
                   fillEmptyRows: false,
                   columns: grid1.Columns(
                    grid1.Column("Sno", header: "S No."),
                    grid1.Column("Name", header: "Vendor Name"),
                    grid1.Column("PurchaseOrderNo", header: "Purchase Order No."),
                    grid1.Column("PurchaseOrderDate", header: "Purchase Order Date"),
                    grid1.Column("IndentRefNo", header: "Purchase Indent No."),
                    grid1.Column("PIDate", header: "Purchase Indent Date"),
                 grid1.Column("GateEntryMidDate", header: "Gate Entry Date"),
                  grid1.Column("GateEntryMidNo", header: "Gate Entry No."),
                   grid1.Column("MRNDate", header: "MRN Date."),
                    grid1.Column("MRN_No_New", header: "MRN No."),
                    grid1.Column("MRN_No_New", header: "Print", canSort: false, format: @<text> @Html.ActionLink("Create MRS ", "GetMRSDetails", "MRNListClassification", new { MRN_NO = ((string)item.MRN_No_New).Replace("/", "#") }, new { target = "_blank" }) </text>)




                       ))

}
else
{
        <p style="color:red; font-size:large">No records found !!!!</p>
    }



</div>