ViewModels/TaxViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MMS.ViewModels
{
    public class TaxViewModel
    {
        public int TransId { get; set; }
        public string TaxCode { get; set; }
        public string TaxType { get; set; }
        public Nullable<decimal> TaxValue { get; set; }
        public Nullable<bool> IsTax { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string TaxStatusExistvalue { get; set; }
        public string Name { get; set; }
        public string TaxNumericValue { get; set; }
    }
}

Controllers/TAX/ExciseDutyController.cs
using MMS.DAL;
using MMS.Models;
using MMS.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MMS.Controllers.TAX
{
    public class ExciseDutyController : Controller
    {
        private MMSEntities objmms = new MMSEntities();
        Procedure objpro = new Procedure();
        // GET: ExciseDuty
        string EmpId = string.Empty;
        string EmpName = string.Empty;
        string ProjectId = string.Empty;

        public  ExciseDutyController()
        {
            try
            {
                ProjectId = System.Web.HttpContext.Current.Session["ProjectssId"].ToString();
                EmpId = System.Web.HttpContext.Current.Session["EmpId"].ToString();
                EmpName = System.Web.HttpContext.Current.Session["Emp_Name"].ToString();

            }
            catch (Exception ex)
            {
                ex.ToString();
            }
        }

        public ActionResult Index()
        {
            List<SelectListItem> objExiceExist = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Select Exice Status", Value = "-1" },
                new SelectListItem { Text = "No", Value = "0" },
                new SelectListItem { Text = "Yes", Value = "1" },
           };
            ViewBag.ExciseDutyStatus = objExiceExist;
            return View();
        }

        public ActionResult AddExcise(ExciseViewModel ex)
        {
            tblMMSExciseDuty obj = new tblMMSExciseDuty();
            var checkEdCode = objmms.tblMMSExciseDuties.Where(x => x.EdCode == ex.EdCode).ToList();
            if (checkEdCode.Count() > 0)
            {
                return Json(new { Status = "2" }, JsonRequestBehavior.AllowGet);
            }
            else {
                // save code here.
                int  S = Convert.ToInt16(ex.ExciseStatusExistvalue);
                if (S == 1)
                {
                    obj.CreatedBy = EmpId;
                    obj.CreatedDate = System.DateTime.Now;
                    obj.EdCode = ex.EdCode;
                    obj.EdType = ex.EdType;
                    obj.EdValue = ex.EdValue;
                    obj.IsExcise = Convert.ToBoolean(S);
                    obj.Status = Convert.ToBoolean(1);
                    obj.IsDeleted = Convert.ToBoolean(0);
                    obj.Remarks = ex.Remarks;
                    objmms.tblMMSExciseDuties.Add(obj);
                }
                else {
                    obj.CreatedBy = EmpId;
                    obj.CreatedDate = System.DateTime.Now;
                    obj.EdCode = ex.EdCode;
                    obj.EdType = ex.EdType;
                    obj.EdValue = Convert.ToDecimal(0.00);
                    obj.IsExcise = Convert.ToBoolean(S);
                    obj.EdNumericValue = ex.EdNumericValue.ToString();
                    obj.Status = Convert.ToBoolean(1);
                    obj.IsDeleted = Convert.ToBoolean(0);
                    obj.Remarks = ex.Remarks;
                    objmms.tblMMSExciseDuties.Add(obj);

                }

               
                objmms.SaveChanges();

                return Json(new { Status = "1" }, JsonRequestBehavior.AllowGet);
            }

          
        }

        public ActionResult GetExice()
        {
            List<_ExciseViewModel> result = new List<_ExciseViewModel>();
            result = objpro.GetExcise();
            if (result != null)
            {
                return PartialView("_ExciseDuties",result);
            }
            else {
                return View("_EmptyView"); 

            }
            
        }


        public ActionResult ChangeStatus(string Id)
        {
            int TrId = Convert.ToInt32(Id);
            tblMMSExciseDuty Im = objmms.tblMMSExciseDuties.Where(x => x.TransID == TrId).First();
            Im.Status = Convert.ToBoolean(0);
            objmms.Entry(Im).State = System.Data.Entity.EntityState.Modified;
            objmms.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ChangeActive(string Id)
        {
            int TrId = Convert.ToInt32(Id);
            tblMMSExciseDuty Im = objmms.tblMMSExciseDuties.Where(x => x.TransID == TrId).First();
            Im.Status = Convert.ToBoolean(1);
            objmms.Entry(Im).State = System.Data.Entity.EntityState.Modified;
            objmms.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

Controllers/TAX/GSTController.cs
using MMS.DAL;
using MMS.Models;
using MMS.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MMS.Controllers.TAX
{
    public class GSTController : Controller
    {
        // GET: GST
        string EmpID = string.Empty;
        private MMSEntities objmms = new MMSEntities();
        Procedure objP = new Procedure();
        public GSTController()
        {
            try
            {
                EmpID = System.Web.HttpContext.Current.Session["EmpID"].ToString();
            }
            catch
            {
            }
        }
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetGSTCode()
        {
            string J = string.Empty;
            J = objP.GetGSTCode();
            var K = new { Code=J };
            return Json(K.ToJSON(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddGST(MMSGSTView Obj)
        {
            tblMMSGSTTaxType gst = new tblMMSGSTTaxType();
            var CheckExist = objmms.tblMMSGSTTaxTypes.Where(x => x.TaxSlabCode == Obj.TaxSlabCode).ToList();
            if (CheckExist.Count() > 0)
            {
                return Json(new { Status = "2" }, JsonRequestBehavior.AllowGet);
            }
            else {

                gst.TaxType = Obj.TaxType;
                gst.TaxSlabCode = Obj.TaxSlabCode;
                gst.TaxSlab = Obj.TaxSlab;
                gst.TaxSlabPercentage = Obj.TaxSlabPercentage;
                gst.CreatedDate = System.DateTime.Now;
                gst.CreatedBy = EmpID;
                gst.Description = Obj.Description;
                objmms.tblMMSGSTTaxTypes.Add(gst);
                objmms.SaveChanges();
                return Json(new { Status = "1" }, JsonRequestBehavior.AllowGet);
            }

         
        }

        public ActionResult GetMMSGST()
        {
            List<MMSGSTView> result = new List<MMSGSTView>();
            result = objP.GetMMSGSTTaxMaster();
            if (result != null)
            {
                return PartialView("_MMSGSTMasterGrid", result);
            }
            else
            {
                return View("_EmptyView");

            }
        }

        public ActionResult AddGST_master()
        {
            return View();
        }

        public JsonResult GetGSTSLAB()
        {
          
            var res = objmms.tblMMSGSTTaxTypes.ToList().Select(x => new { Text = x.TaxSlab, Value = x.TaxSlabCode }).ToList();
           
            return Json(res,JsonRequestBehavior.AllowGet);
        }

        public JsonResult AddSplitGSTMaster(GSTSplit_TaxMasterViewModel obj)
        {
            tblGST_SplitTaxMaster gs_splt = new tblGST_SplitTaxMaster();
            var checkExist = objmms.tblGST_SplitTaxMaster.Where(x => x.TaxRateType == obj.TaxRateType).ToList();
            if (checkExist.Count() > 0)
            {
                return Json(new { Status = "2" }, JsonRequestBehavior.AllowGet);
            }
            else {

                gs_splt.TaxSlabCode = obj.TaxSlabCode;
                gs_splt.TaxSlab = obj.TaxSlab;
                gs_splt.TaxSlabPercentage = objmms.tblMMSGSTTaxTypes.Where(x => x.TaxSlabCode == obj.TaxSlabCode).FirstOrDefault().TaxSlabPercentage;
                gs_splt.CGST = obj.CGST;
                gs_splt.SGST = obj.SGST;
                gs_splt.UGST = obj.UGST;
                gs_splt.IGST = obj.IGST;
                gs_splt.TaxRateType = obj.TaxRateType;
                gs_splt.TaxCode = objP.GetGSTTaxRateCode(); 
                gs_splt.CreatedBy = EmpID;
                gs_splt.CreatedDate = System.DateTime.Now;
                objmms.tblGST_SplitTaxMaster.Add(gs_splt);
                objmms.SaveChanges();
                return Json(new { Status = "1" }, JsonRequestBehavior.AllowGet);
            }
           
        }

        public ActionResult GetSplitGSTMaster()
        {
            List<GSTSplit_TaxMasterViewModel> result = new List<GSTSplit_TaxMasterViewModel>();
            result = objP.GetSplitGSTTaxMaster();
            if (result != null)
            {
                return PartialView("_SplitGSTViewGrid", result);
            }
            else
            {
                return View("_EmptyView");

            }
        }


    }
}

Controllers/TAX/TaxController.cs
using MMS.DAL;
using MMS.Models;
using MMS.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MMS.Controllers.TAX
{
    public class TaxController : Controller
    {
        private MMSEntities objmms = new MMSEntities();
        Procedure objpro = new Procedure();
        // GET: ExciseDuty
        string EmpId = string.Empty;
        string EmpName = string.Empty;
        string ProjectId = string.Empty;

        public TaxController()
        {
            try
            {
                ProjectId = System.Web.HttpContext.Current.Session["ProjectssId"].ToString();
                EmpId = System.Web.HttpContext.Current.Session["EmpId"].ToString();
                EmpName = System.Web.HttpContext.Current.Session["Emp_Name"].ToString();

            }
            catch (Exception ex)
            {
                ex.ToString();
            }
        }
        public ActionResult Index()
        {
            List<SelectListItem> objTaxExist = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Select Tax Status", Value = "-1" },
                new SelectListItem { Text = "No", Value = "0" },
                new SelectListItem { Text = "Yes", Value = "1" },
           };
            ViewBag.TaxStatus = objTaxExist;
            return View();
        }


        public ActionResult AddTax(TaxViewModel ex)
        {
            tblMMSTaxValue obj = new tblMMSTaxValue();
            var checktaxCode = objmms.tblMMSTaxValues.Where(x => x.TaxCode == ex.TaxCode).ToList();
            if (checktaxCode.Count() > 0)
            {
                return Json(new { Status = "2" }, JsonRequestBehavior.AllowGet);
            }
            else {
                // save code here.
                int S = Convert.ToInt16(ex.TaxStatusExistvalue);

                if (S == 1)
                {
                    obj.CreatedBy = EmpId;
                    obj.CreatedDate = System.DateTime.Now;
                    obj.TaxCode = ex.TaxCode;
                    obj.TaxType = ex.TaxType;
                    obj.TaxValue = ex.TaxValue;
                    obj.IsTax = Convert.ToBoolean(S);
                    obj.Status = Convert.ToBoolean(1);
                    obj.IsDeleted = Convert.ToBoolean(0);
                    obj.Description = ex.Description;
                    objmms.tblMMSTaxValues.Add(obj);
                }
                else {
                    obj.CreatedBy = EmpId;
                    obj.CreatedDate = System.DateTime.Now;
                    obj.TaxCode = ex.TaxCode;
                    obj.TaxType = ex.TaxType;
                    obj.TaxValue = Convert.ToDecimal(0.00);
                    obj.IsTax = Convert.ToBoolean(S);
                    obj.Status = Convert.ToBoolean(1);
                    obj.IsDeleted = Convert.ToBoolean(0);
                    obj.Description = ex.Description;
                    obj.TaxNumericValue = ex.TaxNumericValue.ToString();
                    objmms.tblMMSTaxValues.Add(obj);
                }

              
                objmms.SaveChanges();

                return Json(new { Status = "1" }, JsonRequestBehavior.AllowGet);
            }


        }


        public ActionResult GetTax()
        {
            List<_TaxViewModel> result = new List<_TaxViewModel>();
            result = objpro.GetTax();
            if (result != null)
            {
                return PartialView("_Taxdetail", result);
            }
            else {
                return View("_EmptyView");

            }

        }

        public ActionResult ChangeStatus(string Id)
        {
            int TrId = Convert.ToInt32(Id);
            tblMMSTaxValue Im = objmms.tblMMSTaxValues.Where(x => x.TransId == TrId).First();
            Im.Status = Convert.ToBoolean(0);
            objmms.Entry(Im).State = System.Data.Entity.EntityState.Modified;
            objmms.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ChangeActive(string Id)
        {
            int TrId = Convert.ToInt32(Id);
            tblMMSTaxValue Im = objmms.tblMMSTaxValues.Where(x => x.TransId == TrId).First();
            Im.Status = Convert.ToBoolean(1);
            objmms.Entry(Im).State = System.Data.Entity.EntityState.Modified;
            objmms.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Views/Tax/Index.cshtml
@{
    ViewBag.Title = "Index";
    string layout = "";
    var cheking = Session["EmailCheck"].ToString();
    if (cheking == "admin@sitanet.in")
    {
        layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
    else
    {
        layout = "~/Views/Shared/_Layout.cshtml";//
    }
    Layout = layout;

}

<script src="~/Scripts/jquery-1.7.1.js"></script>
<script src="~/Scripts/jquery-1.7.1.min.js"></script>

<link type="text/css" href="~/Content/toastr.min.css" rel="stylesheet" />
<script type="text/javascript" src="~/Scripts/jquery-ui-1.8.20.min.js"></script>
<script type="text/javascript" src="~/Scripts/toastr.min.js"></script>
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<link href="@Url.Content("~/Content/themes/base/minified/jquery-ui.min.css")" rel="stylesheet" type="text/css" />


<script type="text/javascript">

    var SaveTax = '@Url.Action("AddTax", "Tax")';
    var Gettax = '@Url.Action("GetTax", "Tax")';
    var redurl = '@Url.Action("Index", "Tax")';

</script>


<script type="text/javascript">

    $(document).ready(function () {

        $.get(Gettax,

             function (result) {
                 $('#formbody').show();
                 $('#formbody').html(result);

                 $("#loading").hide();
             });



        $('#btnsave').click(function (e) {
            debugger;

            var V = Valid();

            if (V == false)
                return;

            var _griddata = gridToArray();

            var url = SaveTax;
            $.ajax({
                type: 'POST',
                url: url,
                data: JSON.stringify(_griddata),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                processdata: true,

                success: function (json) {
                    debugger;

                    if (json.Status == "1") {

                        alert("Data Saved Successfully");
                        window.location.href = redurl;

                    }
                    else if (json.Status == "2")
                    {
                        alert("Tax code already exist.");
                    }
                    

                },

                error: function () {
                    alert('Error in Submit Data');
                }
            });
        });

        function gridToArray() {
            var obj = new Object();

            obj.TaxCode = $("#txttaxCode").val();
            obj.TaxType = $("#txttaxType").val();
            obj.TaxStatusExistvalue = $("#ddlTaxStatus option:selected").val();

            if ($("#ddlTaxStatus option:selected").val() == 1) {
                obj.TaxValue = $("#txtTaxValue").val();
            } else {
                obj.TaxNumericValue = $("#txtTaxValue").val();
            }
           
            obj.Description = $("#txtDescription").val();

            return obj;

        }


        function Valid() {


            var TaxCode = $("#txttaxCode").val();
            var TaxType = $("#txttaxType").val();
            var TaxStatusExistvalue = $("#ddlTaxStatus option:selected").val();
            var TaxValue = $("#txtTaxValue").val();
            var Description = $("#txtDescription").val();
            var rr = true;


            if (TaxCode == "") {
                alert('Enter the Tax Code.');
                $('#txttaxCode').css('border-color', '#f0551b');

                rr = false;
            }
            else {
                $('#txttaxCode').css('border-color', '');
            }

            if (TaxType == "") {
                alert('Enter the Tax Type.');
                $('#txttaxType').css('border-color', '#f0551b');

                rr = false;
            }
            else {
                $('#txttaxType').css('border-color', '');
            }


            if (TaxValue == "") {
                alert('Enter the Tax Value.');
                $('#txtTaxValue').css('border-color', '#f0551b');

                rr = false;
            }
            else {
                $('#txtTaxValue').css('border-color', '');
            }


            if (TaxStatusExistvalue == "") {

                alert('Select Excise Status.');
                $('#ddlTaxStatus').css('border-color', '#f0551b');

                rr = false;
            }
            else {
                $('#ddlTaxStatus').css('border-color', '');
            }




            if (Description == "") {
                alert('Enter the Description.');
                $('#txtDescription').css('border-color', '#f0551b');

                rr = false;
            }
            else {
                $('#txtDescription').css('border-color', '');
            }




        if (rr == false) {


                return false;
            }
            else {
                return true;
            }
        }






    });
</script>





<section id="content_wrapper">
    <!-- Begin: Content -->
    <section id="content" class="table-layout animated fadeIn">

        <!-- begin: .tray-center -->
        <div class="tray tray-center">

            <div class="mw1000 center-block">
                <div class="admin-form theme-primary">
                    <!-- Begin: Content Header -->
                    <!-- Begin: Admin Form -->
                    <div class="form-headerStyle theme-primary">

                        <div class="panel heading-border">
                            <div class="panel-body bg-light">
                                <div class="section-divider mb40" id="spy1">
                                    <span style="color:#4a89dc">Tax Master</span>
                                </div>

                                <form class="row" id="loginForm">

                                    @using (Html.BeginForm())
                                    {
                                        @Html.AntiForgeryToken()

                                        <div class="form-horizontal">

                                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="section">
                                                        <label class="field prepend-icon">
                                                            @Html.TextBox("TaxCode", null, new { id = "txttaxCode", @class = "form-control gui-input", @placeholder = "Tax Code" })
                                                            <label for="firstname" class="field-icon">
                                                                <i class="fa fa-building"></i>
                                                            </label>
                                                        </label>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="section">
                                                        <label class="field prepend-icon">
                                                            @Html.TextBox("Tax Type", null, new { id = "txttaxType", @class = "form-control gui-input", @placeholder = "Tax Type" })
                                                            <label for="lastname" class="field-icon">
                                                                <i class="fa fa-building"></i>
                                                            </label>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>


                                            <div class="row">
                                                <div class="col-md-6">


                                                    <div class="section">
                                                        <label class="field select">

                                                            @Html.DropDownList("TaxStatus", (IEnumerable<SelectListItem>)ViewBag.TaxStatus, htmlAttributes: new { @id = "ddlTaxStatus", @class = "form-control" })

                                                            <i class="arrow"></i>
                                                        </label>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="section">
                                                        <label class="field prepend-icon">
                                                            @Html.TextBox("TaxValue", null, new { id = "txtTaxValue", @class = "form-control gui-input", @placeholder = "Tax Value" })
                                                            <label for="firstname" class="field-icon">
                                                                <i class="fa fa-building"></i>
                                                            </label>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>



                                            <div class="row">


                                                <div class="col-md-12">
                                                    <div class="section">
                                                        <label class="field prepend-icon">
                                                            @Html.TextArea("Description", null, new { id = "txtDescription", @class = "form-control gui-input", @placeholder = "Description" })
                                                            <label for="firstname" class="field-icon">
                                                                <i class="fa fa-building"></i>
                                                            </label>
                                                        </label>
                                                    </div>
                                                </div>


                                            </div>

                                            <br />
                                            <div class="row">
                                                <div class="col-md-offset-2 col-md-10" style="text-align:right;">

                                                    <input type="button" id="btnsave" class="btn btn-primary" value="Save" />
                                                </div>
                                            </div>

                                        </div>
                                    }




                                </form>

                                <div id="dvLoading"></div>
                                <div id="#progress" style="display:none"><img src="~/Images/36.gif" /></div>
                                <div class="pager glyphicon-align-center" id="formbody">


                                </div>

                                <div class="section-divider mt40 mb25" id="spy5">
                                    <span></span>
                                </div>



                            </div>
                        </div>

                    </div>



                </div>
            </div>
        </div>
        <!-- end: .tray-center -->
        <!-- begin: .tray-right -->
        <!-- end: .tray-right -->

    </section>
    <!-- End: Content -->
</section>

Views/Tax/_Taxdetail.cshtml
<style>
    .gridTable {
        margin: 5px;
        padding: 10px;
        border: 1px #c8c8c8 solid;
        border-collapse: collapse;
        min-width: 550px;
        background-color: #fff;
        color: #fff;
        width: 100%;
    }

    .gridHead th {
        font-weight: bold;
        background-color: #5c93f0;
        color: #fff;
        padding: 5px;
        text-align: center;
        font-size: 12px;
    }

    .gridHead a:link, .gridHead a:visited, .gridHead a:active, .gridHead a:hover {
        color: #fff;
    }

    .gridHead a:hover {
        text-decoration: underline;
    }

    .gridTable tr.gridAltRow {
        background-color: #efeeef;
    }

    .gridTable tr:hover {
        background-color: #7da3f2;
    }

    .gridTable tr :hover {
        color: white;
    }

    .gridAltRow td {
        padding: 10px;
        margin: 5px;
        color: #333;
        text-align: center;
        font-weight: normal;
        font-size: 11px;
    }

    .gridRow td {
        padding: 10px;
        color: #333;
        text-align: center;
        font-weight: normal;
        font-size: 11px;
    }

    .gridFooter td {
        padding: 10px;
        color: #ffffff;
        font-size: 12pt;
        text-align: center;
        background-color: #5c93f0;
    }

    .aaaa {
        width: 60px;
    }




    .gridFooter a {
        text-decoration: none;
        padding: 6px 11px;
        margin-right: 6px;
        border-radius: 3px;
        color: #fff;
        text-shadow: 0px 1px 2px rgba(0, 0, 0, 0.5);
        border: 1px solid #43505e;
        background: #556270;
        background: -moz-linear-gradient(top, #556270 0%, #444d57 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#556270), color-stop(100%,#444d57));
        background: -webkit-linear-gradient(top, #556270 0%,#444d57 100%);
        background: -o-linear-gradient(top, #556270 0%,#444d57 100%);
        background: -ms-linear-gradient(top, #556270 0%,#444d57 100%);
        background: linear-gradient(to bottom, #556270 0%,#444d57 100%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#556270', endColorstr='#444d57',GradientType=0 );
        -moz-box-shadow: inset 0 3px 0px -2px rgba(255, 255, 255, .3);
        -webkit-box-shadow: inset 0 3px 0px -2px rgba(255, 255, 255, .3);
        box-shadow: inset 0 3px 0px -2px rgba(255, 255, 255, .3);
    }
</style>


<div id="gridposition" class="table-responsive" style="width: 100%; ">
    @if (Model.Count > 0)
    {
        var grid1 = new WebGrid(source: Model, canPage: true, canSort: false, rowsPerPage: 20, ajaxUpdateContainerId: "positionGrid");

        @grid1.GetHtml(mode: WebGridPagerModes.All,
                   tableStyle: "gridTable",
                   headerStyle: "gridHead",
                   footerStyle: "gridFooter",
                   rowStyle: "gridRow",
                   alternatingRowStyle: "gridAltRow",
                   htmlAttributes: new { id = "positionGrid" },
                   fillEmptyRows: false,
                   columns: grid1.Columns(
                    grid1.Column("TaxCode", "Tax Code"),
                     grid1.Column("TaxType", "Tax Type"),
                      grid1.Column("TaxValue", "Tax Value"),
                       grid1.Column("Description", "Description"),
                       grid1.Column("CreatedDate", header: "Created Date", format: (item) => string.Format("{0:dd-MMM-yyyy}", item.CreatedDate)) ,

                         grid1.Column("TransId", header: "Action", canSort: false, format: (item) => (bool)item.Status ? Html.ActionLink("Enable", "ChangeStatus",


                       new { Id = item.TransId }, new
                       {
                           onclick = "return confirm('Are you sure wants to disable ?');",
                           style = "color:'red'",
                           onmouseover = "this.style.color='green'",
                           onmouseout = "this.style.color='#5c93f0'"
                       }
                     )
                : Html.ActionLink("Disable", "ChangeActive", new { Id = item.TransId }, new { onclick = "return confirm('Are you sure wants to enable?');", style = "color:'#5c93f0'" }))







                   ))

    }
    else
    {
        <p style="color:red; font-size:large">No records found !!!!</p>
    }



</div>