Controllers/Reports/Datewise_Item_Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MMS.Models;
using MMS.DAL;
using System.Data;
using MMS_P.ViewModels;
using MMS.ViewModels;
using System.Data.Entity;
using System.Linq.Dynamic;
using System.Web.Helpers;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.Text;

namespace MMS.Controllers.Reports
{
    public class Datewise_Item_Controller : Controller
    {
        private MMSEntities objmms = new MMSEntities();
        private UnitOfWork unitOfWork = new UnitOfWork();
        string ProjectId;
        // GET: Non_Moveing_
        [Authorize]
        public ActionResult Index()
        {
            if (Session["EmpID"] == null)
            {
                return RedirectToAction("Login", "MyAccount");
            }

            string empId = Session["EmpID"].ToString();
            string ProjectId = Session["ProId"].ToString();

            Datewise_Item_Model rrm = new Datewise_Item_Model();

            ViewBag.item_Group_name = new SelectList(objmms.tblItemGroupMasters, "ItemGroupID", "GroupName").OrderBy(k => k.Text);
            //ViewBag.Vendor_Name = new SelectList(objmms.GateEntryChilds, "VendorNo", "Vendor").OrderBy(k => k.Text);

            //code for bind vendor name accoding project
            var a = objmms.GateEntryChilds.Where(b => b.ProjectNo == ProjectId).OrderBy(c => c.Vendor).ToList();
            var t = a.Distinct<GateEntryChild>().Select(x => new SelectListItem
            {
                Value = x.VendorNo?.ToString().Trim(),
                Text = x.Vendor?.ToString().Trim()
            });
            ViewBag.Vendor_Name = t;

            //code for bind PO No accoding project
            var a1 = objmms.GateEntries.Where(b1 => b1.ProjectNo == ProjectId).OrderBy(c1 => c1.StatusTypeNo).ToList();
            var t1 = a1.Distinct<GateEntry>().Select(x1 => new SelectListItem
            {
                Value = x1.StatusTypeNo?.ToString().Trim(),
                Text = x1.StatusTypeNo?.ToString().Trim()
            });
            ViewBag.PONumber = t1;

            var data_from_table = (from e in objmms.GateEntryChilds
                                   where e.ProjectNo == ProjectId
                                   orderby e.Date
                                   select new Datewise_Item_Model
                                   {
                                       Date = e.Date,
                                       GateEntryNo = e.GateEntryNo,
                                       Vendor = e.Vendor,
                                       BillNo = "",
                                      /* BillDate = ""*/
                                       StatusTypeNo = e.StatusTypeNo,
                                       CreatedDate = e.CreatedDate,
                                       ItemNo = e.ItemNo,
                                       ItemGroup = e.ItemGroup,
                                       Item = e.Item,
                                       ReceiveQty = e.ReceiveQty,
                                       Unit = e.Unit,
                                       Rate = e.Rate,
                                       TaxAmount = e.TaxAmount,
                                       DeliveryAmount = e.DeliveryAmount,
                                       AllAmount = e.AllAmount,
                                       Amount = e.Amount
                                   }).OrderByDescending(k => k.Date).Take(200).ToList();

            rrm.Datewise_Item = data_from_table;
            TempData["printexcel"] = data_from_table;
            Session["keepdata"] = data_from_table;
            TempData.Keep("printexcel");
            return View("Index", rrm);
        }


        public ActionResult Datewise_Item_Search(string Item_Group_Name, string Vendors_Name, string PONumber, string FromDate, string ToDate)
        {
            string ProjectId = Session["ProId"].ToString();
            List<Datewise_Item_Model> rrm = null;
            var data_rrm = rrm;

            if (PONumber != null && PONumber != "" && Item_Group_Name != null && Item_Group_Name !="" && Vendors_Name != null && Vendors_Name != "" && FromDate != null && ToDate != null && FromDate != "" && ToDate != "")
            {
                DateTime date1 = Convert.ToDateTime(FromDate);
                DateTime date2 = Convert.ToDateTime(ToDate);


                data_rrm = (from e in objmms.GateEntryChilds
                            where e.ProjectNo == ProjectId && e.StatusTypeNo == PONumber && e.VendorNo == Vendors_Name && e.ItemGroupNo == Item_Group_Name && e.Date >= date1 && e.Date <= date2
                            orderby e.Date
                            select new Datewise_Item_Model
                            {
                                Date = e.Date,
                                GateEntryNo = e.GateEntryNo,
                                Vendor = e.Vendor,
                                BillNo = "",
                                /* BillDate = ""*/
                                StatusTypeNo = e.StatusTypeNo,
                                CreatedDate = e.CreatedDate,
                                ItemNo = e.ItemNo,
                                ItemGroup = e.ItemGroup,
                                Item = e.Item,
                                ReceiveQty = e.ReceiveQty,
                                Unit = e.Unit,
                                Rate = e.Rate,
                                TaxAmount = e.TaxAmount,
                                DeliveryAmount = e.DeliveryAmount,
                                AllAmount = e.AllAmount,
                                Amount = e.Amount
                            }).OrderByDescending(k => k.Date).ToList();
                ViewBag.displySumqty = data_rrm.Sum(k => k.ReceiveQty);
                ViewBag.displySumamt = data_rrm.Sum(k => k.Amount);
                TempData["printexcel"] = data_rrm;
                Session["keepdata"] = data_rrm;
                TempData.Keep("printexcel");
            }
            else if (Item_Group_Name != null && Item_Group_Name != "" && FromDate != null && ToDate != null && FromDate != "" && ToDate != "")
            {
                DateTime date1 = Convert.ToDateTime(FromDate);
                DateTime date2 = Convert.ToDateTime(ToDate);


                data_rrm = (from e in objmms.GateEntryChilds
                            where e.ProjectNo == ProjectId && e.ItemGroupNo == Item_Group_Name && e.Date >= date1 && e.Date <= date2
                            orderby e.Date
                            select new Datewise_Item_Model
                            {
                                Date = e.Date,
                                GateEntryNo = e.GateEntryNo,
                                Vendor = e.Vendor,
                                BillNo = "",
                                /* BillDate = ""*/
                                StatusTypeNo = e.StatusTypeNo,
                                CreatedDate = e.CreatedDate,
                                ItemNo = e.ItemNo,
                                ItemGroup = e.ItemGroup,
                                Item = e.Item,
                                ReceiveQty = e.ReceiveQty,
                                Unit = e.Unit,
                                Rate = e.Rate,
                                TaxAmount = e.TaxAmount,
                                DeliveryAmount = e.DeliveryAmount,
                                AllAmount = e.AllAmount,
                                Amount = e.Amount
                            }).OrderByDescending(k => k.Date).ToList();
                ViewBag.displySumqty = data_rrm.Sum(k => k.ReceiveQty);
                ViewBag.displySumamt = data_rrm.Sum(k => k.Amount);
                TempData["printexcel"] = data_rrm;
                Session["keepdata"] = data_rrm;
                TempData.Keep("printexcel");
            }

            else if (Vendors_Name != null && Vendors_Name != "" && FromDate != null && ToDate != null && FromDate != "" && ToDate != "")
            {
                DateTime date1 = Convert.ToDateTime(FromDate);
                DateTime date2 = Convert.ToDateTime(ToDate);


                data_rrm = (from e in objmms.GateEntryChilds
                            where e.ProjectNo == ProjectId && e.VendorNo == Vendors_Name && e.Date >= date1 && e.Date <= date2
                            orderby e.Date
                            select new Datewise_Item_Model
                            {
                                Date = e.Date,
                                GateEntryNo = e.GateEntryNo,
                                Vendor = e.Vendor,
                                BillNo = "",
                                /* BillDate = ""*/
                                StatusTypeNo = e.StatusTypeNo,
                                CreatedDate = e.CreatedDate,
                                ItemNo = e.ItemNo,
                                ItemGroup = e.ItemGroup,
                                Item = e.Item,
                                ReceiveQty = e.ReceiveQty,
                                Unit = e.Unit,
                                Rate = e.Rate,
                                TaxAmount = e.TaxAmount,
                                DeliveryAmount = e.DeliveryAmount,
                                AllAmount = e.AllAmount,
                                Amount = e.Amount
                            }).OrderByDescending(k => k.Date).ToList();
                ViewBag.displySumqty = data_rrm.Sum(k => k.ReceiveQty);
                ViewBag.displySumamt = data_rrm.Sum(k => k.Amount);
                TempData["printexcel"] = data_rrm;
                Session["keepdata"] = data_rrm;
                TempData.Keep("printexcel");
            }

Views/Datewise_Item_/Index.cshtml
@model MMS.Models.Datewise_Item_Model
@{
    ViewBag.Title = "Index";
    string layout = "";
    var cheking = Session["EmailCheck"].ToString();
    if (cheking == "admin@sitanet.in")
    {
        layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
    else
    {
        layout = "~/Views/Shared/_Layout.cshtml";//
    }

    Layout = layout;
}

<script src="~/Scripts/jquery-2.1.1.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<link href="@Url.Content("~/Content/themes/base/minified/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
<script>
    $(function () {
        $("#fromdate").datepicker();
        $("#todate").datepicker();
    });
    

</script>
<style>
    .Amount {
        color: brown;
        font: 200;
    }
</style>

<script type="text/javascript">
    $(document).ready(function () {
        $('#btn_Receipt_Search').click(function (e) {
            //var gr_name = $("#item_Group_names").val();
            //var vr_name = $("#Vendor_Names").val();
            //var from_date = $("#fromdate").val();
            //var to_date = $("#todate").val();

            //if (gr_name == "" || vr_name == "") {
            //    alert('Please fill the value');
            //    return false;
            //} else {
            //    return true;
            //}

            //if (from_date == "" && to_date == "") {
            //    alert('Please select the date');
            //    return false;
            //} else {
            //    return true;
            //}

                e.preventDefault();
                var url = '@Url.Action("Datewise_Item_Search", "Datewise_Item_")';
                $.get(url,
                    { Item_Group_Name: $('#item_Group_names option:selected').val(), Vendors_Name: $('#Vendor_Names option:selected').val(), PONumber: $('#PONumbers option:selected').val(), FromDate: $('#fromdate').val(), ToDate: $('#todate').val() },
                    function (result) {
                        $('#DIV_Receipt_Report').html(result);
                    });




        })
    });
</script>






<section id="content_wrapper">
    <!-- Begin: Content -->
    <section id="content" class="table-layout animated fadeIn">

        <!-- begin: .tray-center -->
        <div class="tray tray-center">

            <div class="mw1000 center-block">
                <div class="admin-form theme-primary">
                    <!-- Begin: Content Header -->
                    <!-- Begin: Admin Form -->
                    <div class="form-headerStyle theme-primary">

                        <div class="panel heading-border">
                            <div class="panel-body bg-light">
                                <div class="section-divider mb40" id="spy1">
                                    <span style="color:#4a89dc">Vendor Wise Receipt</span>
                                </div>
                                <!-- .section-divider -->
                                <!-- Basic Inputs -->
                                <!-- Input Icons -->
                                <form class="row" id="loginForm">

                                    @using (Html.BeginForm())
                                    {
                                        @Html.AntiForgeryToken()

                                        // Here Field data

                                        <div class="form-horizontal">

                                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="col-md-5">
                                                        <div class="section">
                                                            <div class="form-group">
                                                                <label class="field prepend-icon">
                                                                    @Html.TextBox("SelectDate", null, new { @class = "form-control gui-input", @placeholder = "From Date", @id = "fromdate" })
                                                                    <label for="firstname" class="field-icon">
                                                                        <i class="fa fa-calendar"></i>
                                                                    </label>
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="col-md-5">
                                                        <label class="field prepend-icon">
                                                            @Html.TextBox("SelectDate", null, new { @class = "form-control gui-input", @placeholder = "To Date", @id = "todate" })
                                                            <label for="firstname" class="field-icon">
                                                                <i class="fa fa-calendar"></i>
                                                            </label>
                                                        </label>
                                                    </div>
                                                    
                                                </div>

                                                <div class="col-md-12">
                                                    <div class="col-md-3">
                                                        <div class="section">
                                                            <label class="field select">
                                                                @Html.DropDownList("item_Group_name", null, "Select Item Group", htmlAttributes: new { @id = "item_Group_names", @class = "form-control" })
                                                                <i class="arrow"></i>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <div class="section">
                                                            <label class="field select">
                                                                @Html.DropDownList("Vendor_Name", null, "Select Supplier Name", htmlAttributes: new { @id = "Vendor_Names", @class = "form-control" })
                                                                <i class="arrow"></i>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <div class="section">
                                                            <label class="field select">
                                                                @Html.DropDownList("PONumber", null, "Select PO No", htmlAttributes: new { @id = "PONumbers", @class = "form-control" })
                                                                <i class="arrow"></i>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="button" id="btn_Receipt_Search" class="btn btn-danger" value="Search" />
                                                    </div>
                                                </div>

                                                

                                            </div>

                                            <div id="DIV_Receipt_Report">
                                                @Html.Partial("_Datewise_Item_Partial", Model.Datewise_Item)
                                            </div>

                                        </div>
                                        <br />
                                        <div>
                                            @Html.ActionLink("Export to Excel", "GetExcel", "Datewise_Item_", new { @class = "btn btn-primary" })
                                            @Html.ActionLink("Print", "VendorWiseReceiptPdf", "Datewise_Item_", new { @class = "btn btn-primary", @target = "_blank" })
                                        </div>
                                    }



                                </form>
                                <div id="dvLoading"></div>
                                <div id="#progress" style="display:none"><img src="~/Images/36.gif" /></div>
                                <div class="pager glyphicon-align-center" id="formbody">
                                    @*@{Html.RenderAction("Grid", "ViewSendingIndentRequisition");}*@

                                </div>

                                <div class="section-divider mt40 mb25" id="spy5">
                                    <span></span>
                                </div>

                                <!-- end .section row section -->
                                <!-- end .form-footer section -->
                            </div>
                        </div>

                    </div>



                </div>
            </div>
        </div>
        <!-- end: .tray-center -->
        <!-- begin: .tray-right -->
        <!-- end: .tray-right -->

    </section>
    <!-- End: Content -->
</section>

Views/Datewise_Item_/_Datewise_Item_Partial.cshtml
<style>
    .gridTable {
        margin: 5px;
        padding: 10px;
        border: 1px #c8c8c8 solid;
        border-collapse: collapse;
        min-width: 550px;
        background-color: #fff;
        color: #fff;
        width: 100%;
    }

    .gridHead th {
        font-weight: bold;
        background-color: #5c93f0;
        color: #fff;
        padding: 10px;
        text-align: left;
    }

    .gridHead a:link, .gridHead a:visited, .gridHead a:active, .gridHead a:hover {
        color: #fff;
    }

    .gridHead a:hover {
        text-decoration: underline;
    }

    .gridTable tr.gridAltRow {
        background-color: #efeeef;
    }

    .gridTable tr:hover {
        background-color: #7da3f2;
    }

    .gridTable tr :hover {
        color: white;
    }

    .gridAltRow td {
        padding: 10px;
        margin: 5px;
        color: #333;
        text-align: left;
    }

    .gridRow td {
        padding: 10px;
        color: #333;
        text-align: left;
    }

    .gridFooter td {
        padding: 10px;
        color: #ffffff;
        font-size: 12pt;
        text-align: center;
        background-color: #5c93f0;
    }

    .gridFooter a {
        text-decoration: none;
        padding: 6px 11px;
        margin-right: 6px;
        border-radius: 3px;
        color: #fff;
        text-shadow: 0px 1px 2px rgba(0, 0, 0, 0.5);
        border: 1px solid #43505e;
        background: #556270;
        background: -moz-linear-gradient(top, #556270 0%, #444d57 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#556270), color-stop(100%,#444d57));
        background: -webkit-linear-gradient(top, #556270 0%,#444d57 100%);
        background: -o-linear-gradient(top, #556270 0%,#444d57 100%);
        background: -ms-linear-gradient(top, #556270 0%,#444d57 100%);
        background: linear-gradient(to bottom, #556270 0%,#444d57 100%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#556270', endColorstr='#444d57',GradientType=0 );
        -moz-box-shadow: inset 0 3px 0px -2px rgba(255, 255, 255, .3);
        -webkit-box-shadow: inset 0 3px 0px -2px rgba(255, 255, 255, .3);
        box-shadow: inset 0 3px 0px -2px rgba(255, 255, 255, .3);
    }
</style>




<div id="gridposition" style="width: 100%; overflow:scroll">
    @if (Model.Count > 0)
    {
        var grid1 = new WebGrid(source: Model, canPage: true, rowsPerPage: 10, ajaxUpdateContainerId: "positionGrid");

        @grid1.GetHtml(mode: WebGridPagerModes.All,
                      tableStyle: "gridTable",
                      headerStyle: "gridHead",
                      footerStyle: "gridFooter",
                      rowStyle: "gridRow",
                      alternatingRowStyle: "gridAltRow",
                      htmlAttributes: new { id = "positionGrid" },
                      fillEmptyRows: false,
                      columns: grid1.Columns(
                          grid1.Column(header: "Sr.No.", format: @<text><div>@(item.WebGrid.Rows.IndexOf(item) + 1)</div></text>),
                       grid1.Column("Date", header: "Date", format: @<text>@item.Date.ToString("dd/MM/yy")</text>),
                       grid1.Column("GateEntryNo", header: "GRN No."),
                       grid1.Column("Vendor", header: "Name of Vendor"),
                       //grid1.Column("ItemNo", header: "Item No"),
                       //grid1.Column("BillNo", header: "Bill No."),
                       grid1.Column("StatusTypeNo", header: "PO No. "),
                       grid1.Column("CreatedDate", header: "PO Date.", format: @<text>@item.CreatedDate.ToString("dd/MM/yy")</text>),
                       grid1.Column("ItemGroup", header: "Item Group Name"),
                       grid1.Column("Item", header: "Item Name"),
                       grid1.Column("ReceiveQty", header: "Quantity"),
                       grid1.Column("Rate", header: "Rate"),
                       grid1.Column("TaxAmount", header: "Tax Amount"),
                       grid1.Column("DeliveryAmount", header: "Freight amount"),
                       grid1.Column("Amount", header: "Amount", style: "Amount"),
                       grid1.Column("AllAmount", header: "Total Amount")
                       ))
    }
    else
    {
        <p style="color:red; font-size:large">No records found !!!!</p>
    }


</div>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-3"></div>
        <div class="col-md-3"></div>
        <div class="col-md-3" style="text-align:right;">
            @if (ViewBag.displySumqty != null)
            {
                <b>Total Quantity</b>   @ViewBag.displySumqty
            }
        </div>
        <div class="col-md-3" style="text-align:left;">

            @if (ViewBag.displySumamt != null)
            {
                <b>Total Amount</b>     @ViewBag.displySumamt
            }

        </div>
    </div>
</div>